### ISSUE TITLE
Ability to make connections between agents

### ISSUE THREAD

**Issue by mrcbond88** [didx-xyz/aries-cloudapi-python#100]
Invite sent, invitation accepted, send API call back, and then automate the rest. 

Youth must always initiate the connection. The ecosystem partners must not be able to initiate the connection. 

- [x] Endpoint ability to create invitation (partner)
- [x] Endpoint ability to send invitation (partner)
- [x] Endpoint ability to accept the invitation (youth)
- [x] Automate further calls to finish process of establishing a connection

**Comment by morrieinmaas** [comment]
Regarding `Endpoint ability to send invitation (partner)`:

How do we want to implement this. For reasons touched upon [here](Endpoint ability to send invitation (partner)) it would make sense to use the out-pf-band protocol. However, a mian question remaining is:

* How do we want to get the initially created connection from a-to-b (when there is no connection)? According to the [connections RFC](An invitation to connect may be transferred using any method that can reliably transmit text) we can use 'any method that can reliably transmit text'. Still, that needs to happen somehow, but how?

**Comment by mrcbond88** [comment]
We need to make the trust registry in a way that makes sense to us: how does it work, how do we want it to look, where does it live on the ledger? What is the definition? What info does it hold? Is it just the DID? 

We can look at the ToIP TF APIs to figure this out. 
[](https://wiki.trustoverip.org/plugins/servlet/mobile?contentId=76145#content/view/76145
)

**Comment by morrieinmaas** [comment]
Endpoint ability to send invitation (partner) is implied via having a public DID (that later will be part of the trust registry)
