### ISSUE TITLE
Trust registry for agents ** More information required

### ISSUE THREAD

**Issue by mrcbond88** [didx-xyz/aries-cloudapi-python#101]
An agent can either be registered as an issuer with a public DID or as a verifier without a public DID associated with a multi-use invitation.

Issuers - public DID
- [x] Retrieve a list of issuer public DIDs from ledger written by the Yoma Transaction Endorser DID

Verifiers - non-public DID
  - [x] Manage list of verifiers and related context to be able to make connections in the front-end database? This requires more thought on how we want to engineer this.

Trust Registry UI/UX
- [x] Clearly show if yoma members the various ecosystem agent as part of trust registry and in which role they are acting in; issuer/verifier or both

**Comment by morrieinmaas** [comment]
closes #76

**Comment by morrieinmaas** [comment]
spec [here](https://github.com/didx-xyz/aries-cloudcontroller-python/issues/62)

**Comment by morrieinmaas** [comment]
Relevant questions to answer 

Questions:
- Can two versions of the same schema be registered at the same time in the trust registry? (I tend to think so but unsure)
- Is there a disctinction between schemas that can be issued with, and schemas that can be verified with?

**Comment by morrieinmaas** [comment]
closes #76
