### ISSUE TITLE
Request proof

### ISSUE THREAD

**Issue by mrcbond88** [didx-xyz/aries-cloudapi-python#103]
We can use string matching to find a specific string in a credential. 

- [ ] Request proof from a connection ID
- [ ] Create proof request
- [ ] Accept proof request - how do you want to satisfy the proof request
- [ ] Decline proof request - we can remove the presentation exchange record from the wallet

If a request is sent & there is no credential, then you can't prove anything and there's nothing to send back.

- [ ] Unify API between v1 and v2
- [ ] Add Integration tests
- [ ] Add endpoint to retrieve credentials for a proof request

--- Not for V1 ---
Once we have a rating system, we can use predicates to assess level of skill.

- [ ] Filter options on how you can satisfy a proof request

**Comment by morrieinmaas** [comment]
TODO:

[ ] Add retrieve credentials for a requetsed proof

returns list of available credentials based on /present=-proof/credentails{cred_ex_id}/credentials

**Comment by TimoGlastra** [comment]
- [ ] Unify API between v1 and v2
- [ ] Add Integration tests
- [ ] Add endpoint to retrieve credentials for a proof request

**Comment by TimoGlastra** [comment]
@morrieinmaas could you also take a look at https://github.com/didx-xyz/aries-cloudapi-python/issues/129 as part of this PR? So disabling proofs auto-accept where applicable
