### ISSUE TITLE
Replace endpoint return types json/dict with pydantic schemas 

### ISSUE THREAD

**Issue by morrieinmaas** [didx-xyz/aries-cloudapi-python#13]
We can use pydentic models (correlated to the JSON schemas in FastAPI, [see also](https://fastapi.tiangolo.com/tutorial/response-model/)) to replace the rather undefined json returns for as many endpoints as possible. 

1. That'll enable us to provide function signatures for the endpoints
2. We have a better handle on/it is more clear what we have to expect when calling a function
3. We get validation of data structures coherently and for a discount. 
4. We can test this more easily
5. Some other benefits...

Downsides: ? - Please leave them in the comments if you find any.

Happy to work on this. It's more a matter of time/priority. So, it's up for grabs - first come first serve.

**Comment by vineeth14** [comment]
Good Idea! Will also keep this in mind while developing the verifier endpoint.
