### ISSUE TITLE
Endpoint to register (an existing) DID on the ledger

### ISSUE THREAD

**Issue by morrieinmaas** [didx-xyz/aries-cloudapi-python#144]
- [ ] Create a cloudapi endoint that provided a DID registers that DID on the ledger]

Is it required to expose this? Maybe this is more an internal thing. When a tenant get's created and the role is issuer we should register the did on the ledger

**Comment by TimoGlastra** [comment]
Not needed with current setup. Public DID will be created when assigning the role "issuer" to a tenant
