### ISSUE TITLE
Maybe we can add some mechanism to check whether ed25519 verkey is of valid format so if one passes in a junk key by accident or purpose this fails in a desired way

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#152]
Maybe we can add some mechanism to check whether ed25519 verkey is of valid format so if one passes in a junk key by accident or purpose this fails in a desired way

_Originally posted by @morrieinmaas in https://github.com/didx-xyz/aries-cloudapi-python/pull/125#discussion_r743726771_

**Comment by ff137** [comment]
Resolved in #381
