### ISSUE TITLE
ACA-Py configuration for auto-acceptance

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#154]
To make the process of interacting with the fast api as smooth as possible we should enable some auto accept options, while leaving some other auto configurations turned of for security reasons.

## Checklist

- [ ] Connections
	- `auto-accept-invites: true`
	- `auto-accept-requests: true`
	- `auto-ping-connection: true`
- [ ] Credential & Proofs
	- `preserve-exchange-records: false`
- [ ] Credentials
	- `auto-store-credential: true`
		- Not sure if this is safe because indy doesn't verify the contents, but we can always add methods to get a new credential with correct values
	- `auto-respond-credential-proposal: false`
	- `auto-respond-credential-offer: false`
	- `auto-respond-credential-request: false`
- [ ] Proofs
	- `auto-respond-presentation-proposal: false`
	- `auto-respond-presentation-request: false`
	- `auto-verify-presentation: true`

**Comment by mrcbond88** [comment]
@morrieinmaas Please confirm all is done so we can move this bad boy across
