### ISSUE TITLE
Move deploy to better infrastructure

### ISSUE THREAD

**Issue by morrieinmaas** [didx-xyz/aries-cloudapi-python#161]
The current AWS box is at it's limit. CPU pretty much running at 100% when al containers are up. 

Solution:
* spin up a bigger box (more CPU power)

**Comment by TimoGlastra** [comment]
What's the size of the AWS box? runs fine on a $20 DigitalOcean droplet

**Comment by morrieinmaas** [comment]
you'll hve to ask @lohanspies . Also had a 20$ linode that worked a charm. The thing at hand is struggling though.
