### ISSUE TITLE
Separate dev dependencies in requirements.txt into a separate requirements.dev.txt

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#166]
Or use poetry

**Comment by TimoGlastra** [comment]
Also need to clean up a lot of the dependencies. I don't think we're using them all?

**Comment by morrieinmaas** [comment]
You're absolutely right.

**Comment by TimoGlastra** [comment]
Just cleaned the cloudcontroller dependencies

<img width="824" alt="image" src="https://user-images.githubusercontent.com/23165168/141158556-bc9bf697-e56b-4d51-b893-8d95516b46b6.png">

feels good 😁
