### ISSUE TITLE
use single library for http requests

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#173]
currently `httpx` is used for tests, while `requests` is used for the normal app. I think we should use a single HTTP client library for both

**Comment by morrieinmaas** [comment]
agreed

**Comment by TimoGlastra** [comment]
Do you have a preference between the two?  As I understand it now `requests` is very well established and used everywhere while `httpx` is the new kid on the block with nice new features.

But I haven't worked a lot with both of them, so interested to hear your opinion

**Comment by morrieinmaas** [comment]
Hmm, was going to say I don't but tunrs out I do. I'd go with httpx. It's really just as easy to use as requests and comes with some extra niceties.

**Comment by michaelwiles** [comment]
I believe it was I that originally used httpx for http requests in tests.

The reason I went with httpx is that it supports async and [requests doesn't](https://stackoverflow.com/questions/9110593/asynchronous-requests-with-python-requests).

**Comment by michaelwiles** [comment]
I just remembered... the other reason for httpx is because the examples of how to test a fastapi back end were given in httpx.
