### ISSUE TITLE
Provision yoma agent after startup

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#190]
It is currently not possible to set TAA acceptance on startup of the ACA-Py agent. Therefore after startup we need to take the following steps. I'm not sure yet where this needs to happen as we need the yoma acapy api key to do so. (maybe the fastapi?)

- Get TAA and if required (true for sovrin ledgers which yoma will use) and not accepted yet, accept the TAA using a preconfigured AML
- Fetch the public did. If the agent does not have a public did configured yet (how do we determine the DID, using an env var?) we should set the public did which should also update the endpoint on the ledger

**Comment by TimoGlastra** [comment]
For now we are going to do this manually. Write clear documentation on how you can manually complete this step

**Comment by morrieinmaas** [comment]
Maybe this can be a "simple" bash script or similar. It's possible to accept/reject (interact with terminal dialogues (eg see [here](https://stackoverflow.com/questions/3804577/have-bash-script-answer-interactive-prompts) and [here](https://linux.die.net/man/1/yes) )

**Comment by TimoGlastra** [comment]
Hope this PR get's released soon: https://github.com/hyperledger/aries-cloudagent-python/pull/1643
