### ISSUE TITLE
Make header required where possible and fix the mechanism whereby the header is passed in

### ISSUE THREAD

**Issue by morrieinmaas** [didx-xyz/aries-cloudapi-python#20]
Currently the header is not required from the client request in order to attempt processing the request. 

However, most (possibly all) endpoints will try use the auth/token parts from the header to instantiate the aries controller. Making the header required will likely make the app faster because it will error out/fail earlier in particular it fail fail when no header is provided (earlier) instead of when trying ot instantiate the controller (later).

**Comment by michaelwiles** [comment]
AFAICT the mechanism for passing in headers is not exactly correct. 

All my reading of fast api docs say the _name_ of the parameter on the router matches the name of the header.

Please indicate if you disagree...

**Comment by michaelwiles** [comment]
Okay... so I may have misspoke...

I assume this is how it works:

in req_header the client needs to pass in a python compliant map with the api_key and/or some kind of jwt token?

Please can we rather just have 2 separate headers, one for the api key and one for the bearer token (security).

Just feel that is far more explicit and intuitive.

**Comment by morrieinmaas** [comment]
Yes actually couldn't agree more. They should be two different attributes in the header. I've already started looking at this/re-writing this. Good spot!

**Comment by michaelwiles** [comment]
So the two headers we need are the following:

1. x-api-key: this is the one that provides the api key - we receive it like this from the client and pass it on to the aca-py agent
2. Authorization: with vaule: Bearer <token for wallet> (the value that is returned int he create sub wallet call. Also available via the get token for wallet). This will also be sent verbatim onto the server when provided and required - and if not provided when it is needed should arguably just be rejected.

Any other alternative is just way more complicated than this and than it needs to be.

And like I said, there's no reason not to just follow the aca-py standard. Why change things? keep things consistent.

Let's discuss how to handle the stand along agent at our 2 o clock meeting.

**Comment by morrieinmaas** [comment]
I'm fine with renaming the to tokens. 

I still don't understand why passing in the wallet_id is apparently an issue. If you look at the code it's required for the tenant controller to be instantiated. From a client POV they should know their own wallet_id (and jwt_token). Maybe I'm not getting your point at all. So far wonder though why I would get either of the to (maybe wallet_id) from a context somewhere else within the APi call when the client should know this informations and it's really straight forward to just pass it over. 

I'm also not sure about this get_token_for wallet because that token is for authentication and that call will only work when you are authenticate against the ariesagent. Hence you'd either need to have the tenant token already to obtain it again or the api_key, which correct me if I'm wrong in that case should not be known to the client (subwallet holder not YOMA) nor be available as it is now (for hacking away) via env vars.

**Comment by michaelwiles** [comment]
> I'm fine with renaming the to tokens.
> 
> I still don't understand why passing in the wallet_id is apparently an issue. If you look at the code it's required for the tenant controller to be instantiated. 

Don't understand why it is required by the tenant controller. It is not required by the calls to acapy

>From a client POV they should know their own wallet_id (and jwt_token). 

When using a single agent (not multi tenanted) the client does not need to know their wallet_id. Generally the behaviour for a multi tenant agent is the same as the single tenant agent except that multi tenant requires the token (no other differences) so a client does not have to know their wallet id. 

> Maybe I'm not getting your point at all. So far wonder though why I would get either of the to (maybe wallet_id) from a context somewhere else within the APi call when the client should know this informations and it's really straight forward to just pass it over.

> 
> I'm also not sure about this get_token_for wallet because that token is for authentication and that call will only work when you are authenticate against the ariesagent. Hence you'd either need to have the tenant token already to obtain it again or the api_key, which correct me if I'm wrong in that case should not be known to the client (subwallet holder not YOMA) nor be available as it is now (for hacking away) via env vars.

What do you mean by tenant token? I know there is a tenant token in the code but I don't understand what that is. The multitenant calls do not require any token (only the api token) and if it refers to the "yoma agent" that will have it's own stand alone agent so a token is not requried for this either. So there is no tenant token as far as I understand.

That call get _token_for_wallet only requires the x-api-token (nothing else). 

But this whole issue needs to be discussed. How are youth agents going to identify themselves and thus get their token. That call "get_token_for_wallet" (/multitenancy/wallet/{wallet_id}/token) is my going in position for what we will use for getting the authentication token for a youth agent aka user (but of course we're going to need to get the wallet id from somewhere obviously).

**Comment by michaelwiles** [comment]
Based on the discussion on was it Friday 18 June...

1. api key will always be provided
2. token will be provided when available
3. no wallet id or wallet key will be provided in headers (this is not necessary)

Based on the specific requirement of the call that is being done the token and api key will be provided. Api Key is _always_ required though token is sometimes not.

I strongly suggest that we use the standard name for the api key - that is, the same as it is on aca-py: x-api-token. Placing an x before your own custom headers is standard.

And also expect the same mechanism aca-py uses to require the token:

Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ3YWxsZXRfaWQiOiJiOWQ2YjNiOS04Yjc0LTRhMmMtYTkwNy1kM2Q4NzI2MDBkMjQifQ.oMN5frWy36IoTKSgSXjDhvCMqMAAIMewCS0Q5xgefcY

Where authorization is the key and value is Bearer <token>

This is the same token as will be received from the get token in the multi tenant wallet api: endpoint: /multitenancy/wallet/<wallet_id>/token

The front end context will provide the wallet id.

**Comment by morrieinmaas** [comment]
Closing this because this should really be a different issue then. Headers are required now already. The `Authorization: Bearer` part needs implementing
