### ISSUE TITLE
Extracting wallet_id from the JWT without validating it is insecure

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#203]
Currently the cloud api extracts the wallet id from the JWT to determine for which wallet it needs to return the webhook  events. This is insecure as I could forge an invalid JWT (not created by ACA-Py) with any wallet_id. 

We should do a call to the ACA-Py API (any call, not sure which is best) to verify the request will succeed, which means the token can be trusted

**Comment by TimoGlastra** [comment]
Should also check for non-tenant calls, as otherwise you can get access to the  admin wallet webhooks by providing any of the non-tenant roles and a random api key

**Comment by TimoGlastra** [comment]
I've picked this up as part of the endorsement work @morrieinmaas

**Comment by morrieinmaas** [comment]
AH alright. Thanks for letting me know. Let me know if I can help and/or review the PR.
