### ISSUE TITLE
Support revocation

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#204]
We should look at supporting revocation in the cloud api. This is mostly already handled by ACA-Py so we should just look at what is needed in terms of infrastructure and API endpoints. 

- [ ] Add tails server to the infrastructure and provide this to all ACA-Py agents
- [ ] Allow to specify `supports_revocation` when creating a credential definition
- [ ] Add endpoint to revoke a credential by the credential exchange record id or the indy specific identifiers.
- [ ] add tests

This is not a requirement for the V1 Must Have

**Comment by lohanspies** [comment]
@TimoGlastra @morrieinmaas this is the most important next component to include in the Cloud API to have a feature-complete API to be used by Trust Ecosystems.
