### ISSUE TITLE
Create YOMA von-network/ledger

### ISSUE THREAD

**Issue by morrieinmaas** [didx-xyz/aries-cloudapi-python#21]
Create a publically available ledger to replace sovrin stagiung net - 

so that we can replace the GENESIS_URL for local/dev setup

**Comment by morrieinmaas** [comment]
Closes #6

**Comment by lohanspies** [comment]
@morrieinmaas all good. We need to include the tails server for revocation.

**Comment by morrieinmaas** [comment]
@lohanspies ah yeah true. I'll add that.
