### ISSUE TITLE
Check why webhook handler is getting congested

### ISSUE THREAD

**Issue by mrcbond88** [didx-xyz/aries-cloudapi-python#216]
It works for now but it slows down. Not sure if that's becuase of the assigned memory in the docker container is low. Will need to check.

**Comment by morrieinmaas** [comment]
* In general:
    * Works fine for web socket pub/sub
    * Falls over for very frequent polling (because it retrieves all sets of hooks for a wallet on every request)
* What do we want to do
    * Is redid the right choice
        * If not:
            * Use Postgres?
            * Use keyDB?
        * IF yes:
            * How to prevent congestion?:
                * Timestamp feature (implemented on [exp/redis-websocket](https://github.com/didx-xyz/aries-cloudapi-python/tree/exp/redis-websocket))
                * Remove redid altogether (only bridge web hooks)
                    * This removes the storage of old web hooks)
                    * ??? How to handle client wanting to retrieve old data??? 
                    * Other platforms also don’t allow this
* Open questions
    * Authentication in general
        * Is this only for Yoma private net in deploy? 
            * If so, no auth required
            * If not, auth required
    * How to expose pubs/websocket in deploy
        * This is from both a pure infra/setup POV and
        * From security POV (prev point)

**Comment by morrieinmaas** [comment]
Maybe should be "lazy" and do as little as possible in terms of storage/data wrangling and leave being 'good" to the subscriber. However, even in this case should disallow behaviour that makes it slow.
