### ISSUE TITLE
unify issuer and verifier endpoints

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#226]
issuer uses  POST `/generic/issuer/credentials` for send offer and `/generic/issuer/credentials/{credential_id}/request` for send request

verifier uses POST `/generic/verifier/send-request` and `/generic/verifier/accept-request` with the proof id in the body.

will address after #192 

Checklist:
- [ ] make sure all ids are in the same place for the different routes (body vs path)
- [ ] make sure all actions are structured the same way (`send-request` vs `request`)
- [x] make sure the paths are the same `/generic/issuer/credentials/` vs `generic/proofs/send-request`
- [ ] Look at other inconsistencies. Basically you must be able to guess how the api looks by looking at the other api.

**Comment by ff137** [comment]
#623
