### ISSUE TITLE
Document how the webhook server can be used without the fastapi pubsub library.

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#236]
Is this even possible? Should we expose a generic pubsub webhook relay from the cloudapi fastapi so we can keep the webhook server internal?

**Comment by morrieinmaas** [comment]
I'm not 100% sure as I haven't tried this out but I don't see why this shouldn't be possible. If you look at [the code of the PubSubClient of the package used](https://github.com/permitio/fastapi_websocket_pubsub/blob/master/fastapi_websocket_pubsub/pub_sub_client.py) this is an implementation of the PubSub mechanism which is based on [RPC](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/RpcChannel).
    
So if the websocket url get exposed properly, in theory, this should allow an RPC client written in any language to register listeners. The implementation for this project using the Python library is situated in [`app/webhook_listener.py`](https://github.com/didx-xyz/aries-cloudapi-python/blob/development/app/webhook_listener.py). [This](https://cloud.google.com/pubsub/docs/reference/libraries#client-libraries-install-csharp) might be relevant.

Essentially all it *should* take is using any PubSub Client implementation and make it listen on `ws://websocket_url:port/pubsub` passing in the appropriate handler functions and topics to listen on corollary to as it's done in [the Python implementation in this project](https://github.com/didx-xyz/aries-cloudapi-python/blob/development/app/webhook_listener.py).

Hope this helps and let me know if you want you have further questions @lohanspies

**Comment by morrieinmaas** [comment]
@TimoGlastra this has been done, hasn't it?

**Comment by TimoGlastra** [comment]
Don't think so? There's documentation how you can do it with the fastapi library, but I'm not aware of any documentation how to do it without that library

**Comment by morrieinmaas** [comment]
> Don't think so? There's documentation how you can do it with the fastapi library, but I'm not aware of any documentation how to do it without that library

Aight. I'll have a poke at it

**Comment by morrieinmaas** [comment]
Alright, sorted this @lohanspies:

For example(s):

```bash
websocat -E --text ws://127.0.0.1:3010/pubsub exec:'{"request": {"method": "subscribe", "arguments": {"topics": ["proofs", "endorsements", "oob", "out_of_band", "connections", "basic-messages", "credentials"]}}}'
```

```bash
wscat -c ws://127.0.0.1:3010 -x '{"request": {"method": "subscribe", "arguments": {"topics": ["proofs", "endorsements", "oob", "out_of_band", "connections", "basic-messages", "credentials"]}}}' -w 99999
```

That's both run from terminal.

Like I said in the call you should be able to use a subscriber in any language. [Wscat](https://github.com/websockets/wscat) is a javascript library and [websocat](https://github.com/vi/websocat) is written in Rust, but it doesn't matter at all. You 'just' need an rpc client that can subscribe (via sending a message over websocket - in this case `{"request": {"method": "subscribe", "arguments": {"topics": ["proofs", "endorsements", "oob", "out_of_band", "connections", "basic-messages", "credentials"]}}}`).

I'll add this to the docs. 

Hope this helps and clarifies things. Let me know if not or things are unclear.
