### ISSUE TITLE
Ensure error handling provide informative messages when errors occur

### ISSUE THREAD

**Issue by lohanspies** [didx-xyz/aries-cloudapi-python#241]
After playing with the Cloud API I encountered various errors. At the moment some errors are gracefully handled and provide informative information about the error while other boils up from AcaPy directly which makes it very hard to understand exactly where the error occurred.

To solve this we need to enhance error/exception handling to provide informative messages when errors are encountered.

@TimoGlastra @morrieinmaas

**Comment by jasondicker** [comment]
Perhaps this will help..

On my side, the following HTTP request returns an error:

```
POST http://localhost:8000/generic/issuer/credentials
accept: application/json
x-api-key: tenant.eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ3YWxsZXRfaWQiOiIxZGE3MmFlOC1kMmIwLTQ2MjAtYTNmYS1hMjQ2MmEyOWEwYjgifQ.1EMr72so9tmswwpoDEv4rKjy1jWUzngarrNJfDRVdPI

{
  "protocol_version": "v1",
  "connection_id": "6d0761d5-788d-472d-894f-755f441d489e",
  "credential_definition_id": "8YrTYbP5Rqrou5VLjqKNKC:3:CL:10:default",
  "attributes": {
    "skill": "skill1",
    "age": "age1"
  }
}
```

..with the following HTTP response:

```
HTTP/1.1 422 Unprocessable Entity
date: Wed, 08 Jun 2022 05:47:56 GMT
server: uvicorn
content-length: 88
content-type: application/json
connection: close

{
  "detail": [
    {
      "loc": [
        "body"
      ],
      "msg": "value is not a valid dict",
      "type": "type_error.dict"
    }
  ]
}
```

**Comment by ff137** [comment]
Error messages have been approved across the board. Remaining improvements can be inferred from datadog analytics
