### ISSUE TITLE
Credential records should not be deleted for received credentials

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#243]
ACA-Py by default deleted exchange records after a credential has been issued. For issuers this makes sense, to not keep a lot of possibly sensitive data in ACA-Py, but for holders we need the records. The easiest way would be to set `ACAPY_PRESERVE_EXCHANGE_RECORDS=true`, but this means records will be kept for both issuers and holders. 

Otherewise we need to add a service that removes any records from issuers once they transition to state done

**Comment by ff137** [comment]
Resolved to be configurable #552
