### ISSUE TITLE
credential exchange has state none breaking cloud api

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#244]
The following error is returned when retrieving all credentials: 

```
{
	"detail": [
		{
			"loc": [
				"state"
			],
			"msg": "none is not an allowed value",
			"type": "type_error.none.not_allowed"
		}
	]
}
```

Steps to reproduce:
1. offer credential from issuer to holder
2. try to store credential while state is offer-received
3. then retrieve all credentials

**Comment by morrieinmaas** [comment]
I've had this/a similar problem before. I think this comes from the webhooks coming from aca-py actually. Not entirely sure whether this is a bug in cloudapi (htis repo) or possibly aca-py. However, if I'm not mistaken this should never be none (and none inplace of None) hints at this being already wrong in the webhook payload. 

Anyway, I reckon a good short term solution is to be more lax on schema validation and make state either Optional with default none or allow for none. In the end it's probably handier to have a webhook with state: None and the rest of the info as opposed to an error in the first place?!

**Comment by TimoGlastra** [comment]
I think the issue @lohanspies encountered is not with webhooks but with the actual models returned from ACA-Py. I think relaxing the model validation would be good, but if we can create a minimal reproduction I would also really like to open an issue in ACA-Py itself so this can get fixed.

**Comment by morrieinmaas** [comment]
Agreed, opening an issue in Aca-py is a good idea.

**Comment by lohanspies** [comment]
Please add 'abandoned' to the models.
