### ISSUE TITLE
Aries Cloud API don't work with Sovrin Buildernet

### ISSUE THREAD

**Issue by lohanspies** [didx-xyz/aries-cloudapi-python#256]
When creating new tenants using the cloud API with Sovrin Buildernet, the TE/TA protocol breaks.

See error below:
```detail": "Ledger request error. Request failed: client request invalid: UnauthorizedClientRequest('Rule for this action is: 1 TRUSTEE signature is required and needs to be owner OR 1 STEWARD signature is required and needs to be owner OR 1 ENDORSER signature is required and needs to be owner OR 1 NETWORK_MONITOR signature is required and needs to be owner OR 1 signature of any role is required and needs to be owner with additional metadata fees attrib_add OR 1 ENDORSER signature is required AND 1 signature of any role is required and needs to be owner\\nFailed checks:\\nConstraint: 1 TRUSTEE signature is required and needs to be owner, Error: Not enough TRUSTEE signatures\\nConstraint: 1 STEWARD signature is required and needs to be owner, Error: Not enough STEWARD signatures\\nConstraint: 1 ENDORSER signature is required and needs to be owner, Error: Not enough ENDORSER signatures\\nConstraint: 1 NETWORK_MONITOR signature is required and needs to be owner, Error: Not enough NETWORK_MONITOR signatures\\nConstraint: 1 signature of any role is required and needs to be owner with additional metadata fees attrib_add, Error: Fees are required for this txn type\\nConstraint: 1 ENDORSER signature is required AND 1 signature of any role is required and needs to be owner, Error: Not enough ENDORSER signatures',).",```

**Comment by lohanspies** [comment]
And as a result of this error the API freezes when trying to login to the wallet of the newly created tenant.

**Comment by lohanspies** [comment]
@morrieinmaas @TimoGlastra this seems to be fixed with the latest controller and AcaPy version updates.

**Comment by morrieinmaas** [comment]
@lohanspies nice! and thx for checking - hadn't gotten round to it meanwhile
