### ISSUE TITLE
webhooks auth

### ISSUE THREAD

**Issue by morrieinmaas** [didx-xyz/aries-cloudapi-python#259]
Currently the webhooks handler has no auth mechanism. This is a design choice as it is intended to be consumed only by the cloudapi setup internally. 

However, one might want to listen to the filter webhooks via websocket subscriber from a client app (external to cloudapi). If so, some form of auth should be implemented.

Is this a desired feature/change?

Suggestion: 

Auth should cover at least the things:

1. Auth per wallet. A subwallet (client) should only be able listen to its own webhooks corresponding to its wallet id. It should NOT be able to listen to other wallets' hooks nor all webhooks
2. A webhook subscriber for a given wallet should have to pass its Bearer token for authentication.[^1]
3. The exposed websocket endpoint should be secured (wss instead of ws - OUT OF SCOPE  - infra)

[^1]: In order to keep the webhook relay stateless and not having to maintain an auth database it could do a call againt the aca-py instance with the provided header Bearer token to query something for the subwallet (provided wallet_id). If the call returns with status 200 (and not with 401 unathorized) the token is valid. Since the listener connection is keep-alive and not http long poll this should not flood the network. Still feels slightly hacky so other ideas welcome.

**Comment by TimoGlastra** [comment]
I think the approach you describe in the footnote is completely fine @morrieinmaas, and also what we're doing for the webhook endpoints in the cloud API at the moment I believe 👍

**Comment by ff137** [comment]
Auth has since been implemented. The tenant/ and tenant admin/ sse, websocket and webhook endpoints all authenticate that calls are made by admins or relevant tenant_jwt's
