### ISSUE TITLE
Update to aca-py 0.7.5

### ISSUE THREAD

**Issue by morrieinmaas** [didx-xyz/aries-cloudapi-python#261]
aca-py 0.7.5 should be released soon. This release will include some patches for endorsement among other things. we should probably upgrade to this version in the near future.

- [ ] create cloudcontroller version for 0.7.5
- [ ] update cloudapi to use 0.7.5 and corresponding cloudcontroller
- [ ] adjust onboarding flow (and other places) using endorsement
- [ ] adjust tests

**Comment by TimoGlastra** [comment]
I think 0.7.5 has been released now
