### ISSUE TITLE
Support connectionless proof request

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#265]
We need to disable the check for the did in the create-proof-request (not for the schema) as it prevents from creating any proof request.

The flow that should work after this:
- (Prover) call `/generic/verifier/create-request`
- (Prover) call `/generic/connections/oob/create-inivtation`
  - `create_connection` should be false
  - proof request message should be added to the invitation
- (Prover) send oob invitation out of band to holder
- (Holder) call `/generic/connections/oob/accept-invitation`
- (Holder) wait for proofs event for the received proof request
- (Holder) send presentation based on proof request

**Comment by TimoGlastra** [comment]
@morrieinmaas this was requested for the yoma platform, can you take a look at this? I think it should be quite straightforward as al the steps are there, they just need to be tweaked a bit to work together

**Comment by morrieinmaas** [comment]
@TimoGlastra sure thing - lemme have a look at this
