### ISSUE TITLE
Do not nest the oob endpoints under the connection topic

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#267]
You can also use it for connectionless exchanges

**Comment by morrieinmaas** [comment]
Sorry can you formulate that differently please? I'm not sure I get what you mean

**Comment by morrieinmaas** [comment]
@TimoGlastra ?

**Comment by TimoGlastra** [comment]
<img width="616" alt="image" src="https://user-images.githubusercontent.com/23165168/201345247-57a6c6b2-9f62-4f60-b6cf-693ac26e62b1.png">

**Comment by TimoGlastra** [comment]
So instead of `/generic/connections/oob/create-invitation` and `/generic/connections/oob/accept-invitation` we have  `/generic/oob/create-invitation` and  `/generic/oob/accept-invitation`

**Comment by morrieinmaas** [comment]
ah alright thx for clarifying

**Comment by lohanspies** [comment]
@morrieinmaas please add the OOB endpoints under the `out-of-band` API collection tag.
