### ISSUE TITLE
Remove v1-/v2- prefix for attachments in the connections/oob/create-invitation call

### ISSUE THREAD

**Issue by TimoGlastra** [didx-xyz/aries-cloudapi-python#268]
In the cloud api we return the proof id with a v1- or v2- prefix, however we do not strip it in the attachments array of the oob invitation call. We should strip the v1-/v2- prefix

```
"attachments": [{"id": "v2-65e023a5-88f1-4ed4-b9ff-63c36f4eb837", "type": "present-proof"}]
```

Should be sent to ACA-Py as:

```
"attachments": [{"id": "65e023a5-88f1-4ed4-b9ff-63c36f4eb837", "type": "present-proof"}]
```

**Comment by TimoGlastra** [comment]
@morrieinmaas small issue with the connectionless proof request flow. Could you take a look at this?

**Comment by morrieinmaas** [comment]
yes will do. Actually admittedly I saw that but thought we'd want to not strip it (so i manually stripped it in the e2e tests. But as we do want to do that I'll implement the strip before return (no pun intended)
