### ISSUE TITLE
Implement /generic/verifier/proofs/{connection_id} endpoint in cloud api

### ISSUE THREAD

**Issue by JJS-Development** [didx-xyz/aries-cloudapi-python#293]
Good day @TimoGlastra ,

We have a requirement on the aries-cloud-api to have the following endpoint available so that we are able to retrieve proofs per connection_id.
/generic/verifier/proofs/{connection_id}

Hope to see the functionality available soon as we need it to display certain information regarding a connection.

Groetjes

Jurgens

**Comment by morrieinmaas** [comment]
Not the optimal way, but depending on how urgent this is for you can always just use the `/generic/verifier/proofs` GET endpoint and then filter the returned list of `PresentationExchange` by `connection_id`

**Comment by JJS-Development** [comment]
I will use the non-optimal way for now until the feature is available.  
Thank you for your response.

**Comment by morrieinmaas** [comment]
no problem, and feel free to tag me/my handle for things like this then I might be able to help out.
