### ISSUE TITLE
Only require auth Bearer token in header for tenant/sub wallet operations

### ISSUE THREAD

**Issue by morrieinmaas** [didx-xyz/aries-cloudapi-python#35]
Based on the discussion in #20 We want to only have the JWT/Auth Bearer Token and not the wallet ID.

Hence rework the header params accordingly as well as the controller passing. 

TBD: 

* How do we get the appropriate contet from the JWT so we can instantiate the TenantController (requires wallet_id and tenant_jwt)

**Comment by michaelwiles** [comment]
Finally figured out what the wallet id is required by the tenant controller...

We are going to need to take a closer look at the listener and webhook context... the life cycle for a listener cannot possibly be tied the lifecycle of a tenant controller - i.e. listeners should probably not only be registered when a tenant controller is created.

I'm hoping the wallet id that an event is for is embedded in the event that is dispatched. 

Need to do some digging into the AriesTenantController to figure out the thinking behind the webhook listener...

**Comment by morrieinmaas** [comment]
Sounds good, please share any insights you gain from that. Generally, there has been discussion whther the webhook listener really should be a standalone kind of feature/thing. Also both the webhook server as well as the webhook listener can be run independently from our request life cycles (and the app altogether).
