### ISSUE TITLE
`wallet_scheme` appears to be ignored in `ACAPY_WALLET_STORAGE_CONFIG`

### ISSUE THREAD

**Issue by rblaine95** [didx-xyz/aries-cloudapi-python#464]
According to [hyperledger/aries-cloudagent-python](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/config/argparse.py#L1658-L1671), the `ACAPY_WALLET_STORAGE_CONFIG` environment variable maps to the [Indy SDK Postgres Plugin](https://github.com/hyperledger/indy-sdk/tree/main/experimental/plugins/postgres_storage)

```rust
// https://github.com/hyperledger/indy-sdk/blob/main/experimental/plugins/postgres_storage/src/postgres_storage.rs#L377-L398
#[derive(Deserialize)]
pub struct PostgresConfig {
    url: String,
    tls: Option<String>,
    tls_ca: Option<String>,
    // default off
    max_connections: Option<u32>,
    // default 5
    min_idle_time: Option<u32>,
    // default 0, deprecated
    min_idle_count: Option<u32>,
    // default 0
    connection_timeout: Option<u64>,
    // default 5
    wallet_scheme: Option<WalletScheme>,   // default DatabasePerWallet
    database_name: Option<String>,   // default _WALLET_DB
    
    // For TLS
    #[serde(skip)]
    negotiator: Option<OpenSsl>,

}
```

It looks like `wallet_scheme` is being ignored when set via the `ACAPY_WALLET_STORAGE_CONFIG` environment variable (`environments/governance-multitenant/aca-py-agent.default.env`)

**Comment by rblaine95** [comment]
🤔 
https://github.com/hyperledger/aries-askar/blob/main/askar-storage/src/backend/postgres/provision.rs#L28-L41

**Comment by rblaine95** [comment]
```sh
for ((i=0; i<10; i++)); do
curl -s -X 'POST' \
  'http://localhost:8100/admin/tenants' \
  -H 'Content-Type: application/json' \
  -H 'x-api-key: adminApiKey' \
  -d @- <<EOF
{
  "image_url": "https://api.dicebear.com/7.x/pixel-art/svg?seed=somethingradnom",
  "name": "my-issuer",
  "roles": [
    "issuer"
  ],
  "group_id": "someGroup"
}
EOF
done
```
The above loop results in a Database Per Wallet being created, even if `ACAPY_WALLET_STORAGE_CONFIG={"url":"governance-multitenant-wallets-db:5432","scheme":"MultiWalletSingleTable","max_connections":50}
`

**Comment by rblaine95** [comment]
https://github.com/hyperledger/aries-cloudagent-python/issues/2043#issuecomment-1344532882 uses `wallet_scheme`
https://github.com/hyperledger/aries-cloudagent-python/issues/2074#issuecomment-1402311748 uses `scheme`

**Comment by rblaine95** [comment]
This looks very much related to [didx-xyz/acapy-wallet-groups-plugin](https://github.com/didx-xyz/acapy-wallet-groups-plugin)

**Comment by ff137** [comment]
The following issue links to documentation for migrating indy wallets using MultiWalletSingleTable to askar:
https://github.com/hyperledger/aries-acapy-tools/issues/7

**Comment by ff137** [comment]
This seems to be what we're missing: [`--multitenancy-config`](https://github.com/hyperledger/aries-cloudagent-python/blob/b8c00ecd21fa3aad78fe86ef869bf872d0c77044/aries_cloudagent/config/argparse.py#L1801)
As mentioned in aries-askar readme, to use [`wallet_type=askar-profile`](https://github.com/hyperledger/aries-acapy-tools/blob/b1e5da552f082b2f1cb283f2f453a37ad6751646/README.md?plain=1#L129)
