### ISSUE TITLE
Trust registry entry inconsistency for tenant with issuer and verifier roles

### ISSUE THREAD

**Issue by wdbasson** [didx-xyz/aries-cloudapi-python#489]
When creating a tenant with issuer and verifier roles the trust registry entry should state the public DID of the entity (the same as issuer trust registry additions)

When creating an invitation and setting use_public_did = true we struggle to make connections with mobile wallets. Not sure if it is related to the bug above

**Comment by ff137** [comment]
Resolved in #545
