### ISSUE TITLE
Create wallet endpoints

### ISSUE THREAD

**Issue by mrcbond88** [didx-xyz/aries-cloudapi-python#51]
Wallet endpoints to be created: (everything in AcaPy)
- [x] list all dids
- [x] create local did
- [x] rotate-keypair
- [x] assign public did

**Comment by mrcbond88** [comment]
@lohanspies what is the difference between **create local did** and **create pub did?**
Do you want two separate end points?

**Comment by mrcbond88** [comment]
What does the call **"Create DID"** do in the Cloud Controller? 
@vineeth14 @morrieinmaas please go through the docs to figure this out and then post a little line here so we can follow?

**Comment by lohanspies** [comment]
@mrcbond88 
Create local DID is just creating a DID without making it public. i.e. A holder DID.
Public DID is pretty obvious, create a DID and then make it public.

**Comment by mrcbond88** [comment]
@vineeth14  FYI

**Comment by mrcbond88** [comment]
Tasks are complete, now moving onto tests.

**Comment by mrcbond88** [comment]
Bug was finally solved. Tests being written. PR up for review shortly.
