### ISSUE TITLE
Issuer V1

### ISSUE THREAD

**Issue by mrcbond88** [didx-xyz/aries-cloudapi-python#52]
All V1 issuer calls from AcaPy 

- [ ] Send holder a credential, automating the entire flow
- [ ] Fetch all credential exchange records
- [ ] Fetch single credential
- [ ] Remove an existing credential
- [ ] Send holder a credential
- [ ] Send a problem report
- [ ] Send holder a credential offer
- [ ] Send issuer credential request
- [ ] Store a received credential
- [ ] Send holder a credential offer
- [ ] Send issuer a credential proposal

**Comment by wip-abramson** [comment]
https://github.com/bcgov/aries-vcr-issuer-controller/blob/master/issuer_controller/src/issuer.py

**Comment by mrcbond88** [comment]
- Monday update: controller version bumped to v2.8.
- Tests are failing, @michaelwiles will take a look
