### ISSUE TITLE
Update the open api definition (swagger) for our api and publish it on insomnia

### ISSUE THREAD

**Issue by mrcbond88** [didx-xyz/aries-cloudapi-python#57]
Define interface for clients to be able to call an API.

This will also give us a clear definition of what the API does.

**Comment by michaelwiles** [comment]
Have started this. clone the cloud api repo into insomnia and you'll get some results.

For help on doing this:

To add it to insomnia you need to do the following:
1. open designer, click create (purpose button top right), click clone
2. enter github location of cloudapi (https) - enter email, name and username (github username)
3. you'll need to get a personal access token - follow the instructions in the link to generate the access token
4. This will then fetch the current version

Am going to cleanup the tags etc to make the generated openapi spec more useful.

**Comment by michaelwiles** [comment]
I've done some work on this - clone the cloud api repo in insomnia and you'll see what's happening

**Comment by michaelwiles** [comment]
I'm going to work a little on fixing the tags and making the generated yaml better.
