### ISSUE TITLE
Add von-network

### ISSUE THREAD

**Issue by vineeth14** [didx-xyz/aries-cloudapi-python#90]
Add the capability to use the local von network to the cloudapi

**Comment by mrcbond88** [comment]
Having issues with GitHub actions. It works locally but doesn't work with GitHub.

@morrieinmaas investigating this

- Failed attempt: Tried using a GitHub project that allows GitHub actions to run locally, but it doesn't work locally for some reason. 
- Something to do with Docker not being happy with localhost. The routing for Docker-in-Docker doesn't seem to work.  Containers are destroyed which means we aren't able to get all the failed info we need.

**Comment by morrieinmaas** [comment]
done

**Comment by mrcbond88** [comment]
In the end it was the Github runner that was slow as well as cached items.
It works locally and remotely, however two tests don't pass on @vineeth14 's side. We need to look into this.
